List = collection of data objects

numpy.array = it is the list with the same data type obejects

a package has to be imported every time session to be used perfectly

In [6]:
import numpy as np
a = np.array([9, 2, 4, 1, 3])
b = np.array((9, 2, 4, 1, 3), dtype = 'f')
print (a)
print(b)

[9 2 4 1 3]
[9. 2. 4. 1. 3.]


In [4]:
a.dtype

dtype('int32')

In [7]:
b.dtype

dtype('float32')

if you do not specify the data type explicitly then python automatically detects the type and then use them in the array as per the concepts of dynamic programming

# Numpy (Dimensions)

In [2]:
import numpy as np

In [16]:
a = np.array([[1, 3, 4], [4, 5, 6]])

note :- when using multidimentional arrays then the number of each dimention should remain constant.

In [9]:
print(a.ndim)

2


ndim = tells how many dimentions are there in the specified array

In [12]:
b = np.array([[[1, 2, 3], [4, 5, 6]], [[3, 2, 4],[2, 5, 1]]])

you can also add arrays of two different arrays

In [9]:
a.ndim

2

In [11]:
b.ndim

3

In [13]:
a

array([[1, 3, 4],
       [4, 5, 6]])

In [17]:
b

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 4],
        [2, 5, 1]]])

In [18]:
b[1, 1, 1]

5

In [20]:
b.ndim

3

In [22]:
type (b)

numpy.ndarray

# Shapes

In [25]:
b = np.array([[[1, 2, 3], [4, 5, 6]], [[3, 2, 4],[2, 5, 1]]])

In [26]:
b.shape

(2, 2, 3)

here the first element show the how many 2 dimentional arrays are there (here 2 in our case), how many 1-D arrays are there (here 2 in our case) and the last one shows how many elements are there in the 1-D element

In [27]:
A = np.array([2])

In [28]:
A.ndim

1

In [29]:
B = np.array(3)

In [30]:
B.ndim

0

In [31]:
b.size

12

In [32]:
b.nbytes

48

.size = shows the size of the array
.nbytes = shows the number of bytes that the array is holing in the memory

In [41]:
A = np.arange(100, 1, -2)

In [42]:
print(A)

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [43]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [47]:
A = np.random.permutation(np.arange(10))
print(A)

[4 6 8 0 2 3 1 5 7 9]


In [53]:
v = np.random.randint(10, 65)
print (v)

45
